package com.kompasid.netdatalibrary.android.screens.enums

enum class Screens(val route: String) {
    ARTICLES_EXAMPLE("ARTICLES_EXAMPLE"),
    EXAMPLE_SCREEN("EXAMPLE_SCREEN"),
    MAIN_SCREEN("MAIN_SCREEN"),
    LAUNCH_APP_SCREEN("LAUNCH_APP_SCREEN"),
    AUTH_SCREEN("AUTH_SCREEN"),
    ACCOUNT_SCREEN("ACCOUNT_SCREEN"),
    NO_ARG_MODULE_SETTINS("NO_ARG_MODULE_SETTINS"),
}