name: Loc - AAA Coba Coba

on:
  workflow_dispatch:

defaults:
  run:
    shell: zsh --login --errexit --pipefail {0}


jobs:
  coba:
      uses: ./.github/workflows/notification_hosted.yml
      with:
        webhook: "${{ vars.WEBHOOK_TEAMS_IOS_LIBRARY }}"
        github_version: "0.0.1"
        github_state: "failure"