name: Loc - Generate Library

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version : "
        required: true
        default: ""
        type: string

defaults:
  run:
    shell: zsh --login --errexit --pipefail {0}

jobs:
  user_informations:
    uses: ./.github/workflows/user_informations.yml

  deploy_library_ios:
    uses: ./.github/workflows/deploy_library_ios_hosted.yml
    with:
      github_version: "${{ github.event.inputs.version }}"
      webhook: ""
      github_actor: "${{ github.actor }}"
      github_triggering_actor: "${{ github.triggering_actor }}"
      github_job: "${{ github.job }}"
      github_ref: "${{ github.ref }}"
      github_workflow_ref: "${{ github.workflow_ref }}"
      