name: GR - Wipe Github Actions on Github Runner Linux

on:
  workflow_call:
    secrets:
      pat:
        required: true


jobs:
  gs_wipe_github_action_cache:
    name: Wipe Github Actions Cache
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Clear caches
        uses: easimon/wipe-cache@main
        with:
          dry-run: "false"