name: GS - Delete Workflow (Cron)

on:
  workflow_call:
    secrets:
      pat:
        required: true



jobs:
  gs_delete_workflow_cron:
    name: Automatically Delete Workflow
    runs-on: [self-hosted, Linux, node20]

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.pat }}
          repository: ${{ github.repository }}
          retain_days: "14"
          keep_minimum_runs: "0"
          delete_workflow_by_state_pattern: "ALL"
          delete_run_by_conclusion_pattern: "ALL"
          dry_run: false