name: Loc - AAA Coba

on:
  workflow_dispatch:
    inputs:
      index:
        description: "Index of the user (0 for irfan, or 1 2 3)"
        required: true
        default: "0"
        type: string

defaults:
  run:
    shell: zsh --login --errexit --pipefail {0}

# concurrency:
#   group: ${{ github.ref }}-${{ github.workflow }}
#   cancel-in-progress: true

jobs:
  coba:
    name: coba
    runs-on: mk-mac-ios-01
    timeout-minutes: 5

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Print User Data
        env:
          USER_DATA: ${{ vars.USER_DATA }}
          INDEX: ${{ github.event.inputs.index }}
        run: |
          echo "Reading user data at index $INDEX"
          USER=$(echo "$USER_DATA" | jq -r ".[$INDEX]")
          echo "User: $USER"
          
          USERNAME=$(echo "$USER" | jq -r ".username")
          FULLNAME=$(echo "$USER" | jq -r ".fullname")
          EMAIL=$(echo "$USER" | jq -r ".email")
          
          echo "Username: $USERNAME"
          echo "Full Name: $FULLNAME"
          echo "Email: $EMAIL